// RSS feed + sitemap generator for the lotusmarket GitHub Pages site.
// Both files are static, regenerated by the workflow whenever a new report
// or blog post lands in docs/.
package main

import (
	"context"
	"fmt"
	"html"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	siteURL     = "https://ducnhd.github.io/lotusmarket"
	feedTitle   = "lotusmarket — Daily VN stock reports"
	feedDesc    = "Auto-generated Vietnamese stock market reports + open-source toolkit updates. Free, deterministic, no hot picks."
	rssMaxItems = 30
)

type feedEntry struct {
	Title   string
	URL     string
	Date    time.Time
	Body    string // optional, used for blog posts
	Section string // "report" | "blog"
}

func collectFeedEntries(docsDir string) []feedEntry {
	var items []feedEntry

	// Reports: docs/reports/YYYY-MM-DD.md
	reportsDir := filepath.Join(docsDir, "reports")
	if entries, err := os.ReadDir(reportsDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".md")
			if name == "index" {
				continue
			}
			t, err := time.Parse("2006-01-02", name)
			if err != nil {
				continue
			}
			// Pin reports to 15:30 VN = 08:30 UTC for stable ordering
			t = t.Add(8*time.Hour + 30*time.Minute)
			items = append(items, feedEntry{
				Title:   fmt.Sprintf("📊 Daily VN stock report — %s", name),
				URL:     fmt.Sprintf("%s/reports/%s.html", siteURL, name),
				Date:    t,
				Section: "report",
			})
		}
	}

	// Blog: docs/blog/*.md
	blogDir := filepath.Join(docsDir, "blog")
	_ = filepath.WalkDir(blogDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(d.Name(), ".md") {
			return nil
		}
		name := strings.TrimSuffix(d.Name(), ".md")
		body, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		title, date := parseBlogFrontmatter(string(body))
		if title == "" {
			title = name
		}
		items = append(items, feedEntry{
			Title:   "📝 " + title,
			URL:     fmt.Sprintf("%s/blog/%s.html", siteURL, name),
			Date:    date,
			Body:    string(body),
			Section: "blog",
		})
		return nil
	})

	sort.Slice(items, func(i, j int) bool { return items[i].Date.After(items[j].Date) })
	if len(items) > rssMaxItems {
		items = items[:rssMaxItems]
	}
	return items
}

// parseBlogFrontmatter pulls `title:` and `date:` out of a YAML frontmatter
// block; falls back to filename + file mtime on the caller side.
func parseBlogFrontmatter(body string) (title string, date time.Time) {
	if !strings.HasPrefix(body, "---") {
		return "", time.Now()
	}
	end := strings.Index(body[3:], "---")
	if end < 0 {
		return "", time.Now()
	}
	for _, line := range strings.Split(body[3:end+3], "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "title:") {
			title = strings.Trim(strings.TrimSpace(strings.TrimPrefix(line, "title:")), `"`)
		}
		if strings.HasPrefix(line, "date:") {
			d := strings.TrimSpace(strings.TrimPrefix(line, "date:"))
			if t, err := time.Parse("2006-01-02", d); err == nil {
				date = t
			}
		}
	}
	if date.IsZero() {
		date = time.Now()
	}
	return
}

func runFeed(ctx context.Context, docsDir string) {
	items := collectFeedEntries(docsDir)
	now := time.Now().UTC().Format(time.RFC1123Z)

	// RSS 2.0
	var rss strings.Builder
	rss.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	rss.WriteString(`<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">` + "\n<channel>\n")
	fmt.Fprintf(&rss, "<title>%s</title>\n", html.EscapeString(feedTitle))
	fmt.Fprintf(&rss, "<link>%s/</link>\n", siteURL)
	fmt.Fprintf(&rss, "<description>%s</description>\n", html.EscapeString(feedDesc))
	fmt.Fprintf(&rss, "<language>vi</language>\n")
	fmt.Fprintf(&rss, "<lastBuildDate>%s</lastBuildDate>\n", now)
	fmt.Fprintf(&rss, `<atom:link href="%s/feed.xml" rel="self" type="application/rss+xml" />`+"\n", siteURL)
	for _, e := range items {
		fmt.Fprintf(&rss, "<item>\n")
		fmt.Fprintf(&rss, "  <title>%s</title>\n", html.EscapeString(e.Title))
		fmt.Fprintf(&rss, "  <link>%s</link>\n", e.URL)
		fmt.Fprintf(&rss, "  <guid isPermaLink=\"true\">%s</guid>\n", e.URL)
		fmt.Fprintf(&rss, "  <pubDate>%s</pubDate>\n", e.Date.UTC().Format(time.RFC1123Z))
		fmt.Fprintf(&rss, "  <category>%s</category>\n", e.Section)
		if e.Section == "blog" && e.Body != "" {
			snippet := stripFrontmatter(e.Body)
			if len(snippet) > 500 {
				snippet = snippet[:500] + "…"
			}
			fmt.Fprintf(&rss, "  <description>%s</description>\n", html.EscapeString(snippet))
		} else {
			fmt.Fprintf(&rss, "  <description>Auto-generated daily report for the VN stock market. View on the dashboard.</description>\n")
		}
		fmt.Fprintf(&rss, "</item>\n")
	}
	rss.WriteString("</channel>\n</rss>\n")

	if err := os.WriteFile(filepath.Join(docsDir, "feed.xml"), []byte(rss.String()), 0644); err != nil {
		panic(err)
	}

	// sitemap.xml — include landing + latest + all reports + all blog
	var sm strings.Builder
	sm.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	sm.WriteString(`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">` + "\n")
	urls := []struct {
		loc      string
		lastmod  time.Time
		priority string
	}{
		{siteURL + "/", time.Now(), "1.0"},
		{siteURL + "/latest.html", time.Now(), "0.9"},
		{siteURL + "/reports/", time.Now(), "0.6"},
	}
	for _, e := range items {
		urls = append(urls, struct {
			loc      string
			lastmod  time.Time
			priority string
		}{e.URL, e.Date, "0.5"})
	}
	for _, u := range urls {
		fmt.Fprintf(&sm, "  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n    <priority>%s</priority>\n  </url>\n",
			u.loc, u.lastmod.UTC().Format("2006-01-02"), u.priority)
	}
	sm.WriteString("</urlset>\n")

	if err := os.WriteFile(filepath.Join(docsDir, "sitemap.xml"), []byte(sm.String()), 0644); err != nil {
		panic(err)
	}

	// robots.txt — point crawlers at sitemap
	robots := fmt.Sprintf("User-agent: *\nAllow: /\nSitemap: %s/sitemap.xml\n", siteURL)
	if err := os.WriteFile(filepath.Join(docsDir, "robots.txt"), []byte(robots), 0644); err != nil {
		panic(err)
	}

	fmt.Fprintf(stderrW(), "wrote feed.xml (%d items), sitemap.xml (%d urls), robots.txt\n", len(items), len(urls))
}

func stripFrontmatter(body string) string {
	if !strings.HasPrefix(body, "---") {
		return body
	}
	end := strings.Index(body[3:], "---")
	if end < 0 {
		return body
	}
	return strings.TrimSpace(body[end+6:])
}
